name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: althack/ros:noetic-dev
      options: --user 1001
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          git submodule update --init --recursive
          sudo apt update
          sudo apt install libenchant-2-dev -y python3-empy zip
          python3 -m pip install --upgrade pip
          apt install python3.8-venv -y
          python3 -m venv docs-env
          ls
          ls docs-env
          ls docs-env/bin
          . docs-env/bin/activate
          pip install -r requirements.txt
          cd _modules/mirte-python
          pip install .
          pip install empy==3.3.4
          cd ../catkin_ws/src/mirte-ros-packages
          ls | grep -xv "mirte_msgs" | xargs rm -rf
          cd ../../
          catkin_make # or catkin build
          . devel/setup.sh
          cd ../../
          make html
          zip -r _build/html.zip _build/html
      - name: install nodejs for archive script
        run: |
          curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt-get install -y nodejs        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            _build/html.zip
